---
title: "Assignment 6 - Walmart data"
author: "Britney Nguyet Dang"
date: '2022-07-11'
output: 
  html_document:
    theme: readable
    highlight: breezedark
    number_sections: yes
    toc: yes
    fig_width: 15
    fig_height: 10
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages, prepare and inspect the data
```{r Load packages, prepare and inspect the data}
#1A
## Load Packages
library(C50)
library(psych)
library(RWeka)
library(rJava)
library(caret) 
library(rminer) 
library(matrixStats)
library(knitr) 
library(arules)
library(Matrix)
library(rpart)
library(rpart.plot)
library(tictoc)
tic()

## Set Directory
mydir <- getwd()
setwd(mydir)

## Import Data
Walmart_data <- read.csv(file="Walmart_visits_7trips.csv",stringsAsFactors = TRUE)
str(Walmart_data)

## Transform Data 
Walmart_data$TripType <- factor(Walmart_data$TripType)
Walmart_data$UniqueItems <- factor(Walmart_data$UniqueItems)
Walmart_data$TotalQty <- factor(Walmart_data$TotalQty)
Walmart_data$RtrnQty <- factor(Walmart_data$RtrnQty)
Walmart_data$NetQty <- factor(Walmart_data$NetQty)
Walmart_data$UniqDepts <- factor(Walmart_data$UniqDepts)
Walmart_data$OneItemDepts <- factor(Walmart_data$OneItemDepts)
Walmart_data$RtrnDepts <- factor(Walmart_data$RtrnDepts)

## Summary
summary(Walmart_data)

#1B Use pairs.panels to understand the data set
pairs.panels(Walmart_data[c("TripType","DOW","UniqueItems","TotalQty","RtrnQty","NetQty","UniqDepts","OneItemDepts","RtrnDepts")])
pairs.panels(Walmart_data[c("TripType","UniqueItems","TotalQty")])
pairs.panels(Walmart_data[c("TripType","RtrnQty","RtrnDepts")])
pairs.panels(Walmart_data[c("TripType","DOW","UniqueItems")])

#1C Build a descriptive C5.0 decision tree using the entire data set
## Build decision tree
Walmart.C50.1 <- C5.0(Walmart_data$TripType~.,Walmart_data)

## Adjust CF value to prune the tree CF=0.15 (leaves < 15)
Walmart.C50.2 <- C5.0(Walmart_data[-1],Walmart_data$TripType,control=C5.0Control(CF=0.15))

## Plot tree 2
plot(Walmart.C50.2)

## Summary
summary(Walmart.C50.2)

## Confusion matrix
predicted.C50.2 <- predict(Walmart.C50.2,Walmart_data)

summary(predicted.C50.2)

mmetric(Walmart_data$TripType,predicted.C50.2,metric="CONF")
```

# Use SimpleKMeans clustering
```{r Use SimpleKMeans clustering}
#2A Create variable TripType.levels and save the number of unique TripType
## Create TripType.levels
TripType.levels <- unique(Walmart_data$TripType)

## Remove "TripType" from data
Walmart_data$TripType <- NULL

## The number of clusters equals to TripType.levels which is 7 (for 2B, 2C, 2D)
nClusters <- 7

#2B SimpleKmeans with random initial cluster assignment (Euclidean distance)
Walmart.clustering.1 <- SimpleKMeans(Walmart_data, Weka_control(N=nClusters, init = 0, V=TRUE))
Walmart.clustering.1

#2C SimpleKMeans with Kmeans++ initial cluster assignment (Euclidean distance)
Walmart.clustering.2 <- SimpleKMeans(Walmart_data, Weka_control(N=nClusters, init=1,  V=TRUE))
Walmart.clustering.2

#2D SimpleKmeans with Kmeans++ initial cluster assignment and "weka.core.Manhattandistance"
Walmart.clustering.3 <- SimpleKMeans(Walmart_data, Weka_control(N=nClusters, init=1, A="weka.core.ManhattanDistance", V=TRUE))
Walmart.clustering.3

#2E Choose my own distance function and initial cluster assignment method, and number of clusters
## 2 clusters, Kmeans++, Euclidean distance 
Walmart.clustering.4 <- SimpleKMeans(Walmart_data, Weka_control(N=2, init=1, V=TRUE))
Walmart.clustering.4
```

# Market Basket Analysis with the Walmart dept baskets
```{r Market Basket Analysis with the Walmart dept baskets}
#3A Import new dataset "Walmart_baskets_1week.csv"
Dept_baskets <- read.transactions("Walmart_baskets_1week.csv", format="single", sep = ",", header = TRUE, cols=c("VisitNumber","DepartmentDescription"))

summary(Dept_baskets)

#3B Inspect the first 15 transactions
inspect(Dept_baskets[1:15])

#3C Plot the most frequent 15 items in the descending order of transaction frequency in percentage
## Examine the frequency of items
itemFrequency(Dept_baskets, type="relative")

## Plot the most frequent 15 items 
itemFrequencyPlot(Dept_baskets, type="relative", topN = 15)

#3D Associate rule mining
## Generate 50 to 100 association rules
### Set threshold support = 0.05, confidence = 0.08 (set of 99 rules)
rules50to100 <- apriori(Dept_baskets, parameter = list(support = 0.05, confidence = 0.08))
summary(rules50to100)

### Sort desc order by "lift"
inspect(sort(rules50to100,by = "lift"))

## Generate 100 to 200 association rules
### Set threshold support = 0.038, confidence = 0.06 (set of 193 rules)
rules100to200 <- apriori(Dept_baskets, parameter = list(support = 0.038, confidence = 0.06))
summary(rules100to200)

### Sort desc order by "lift"
inspect(sort(rules100to200,by = "lift"))
```
